# Generated by Django 3.2 on 2023-05-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'user',
                'ordering': ['user_id'],
            },
        ),
    ]
