# Generated by Django 3.2.18 on 2023-04-27 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'user',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Wordbook',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='単語')),
                ('meaning', models.TextField(verbose_name='意味')),
                ('pronunciation', models.CharField(blank=True, max_length=50, null=True, verbose_name='発音')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='品詞')),
                ('context', models.TextField(blank=True, null=True, verbose_name='文脈')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.users', verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '単語帳',
                'verbose_name_plural': '単語帳',
                'db_table': 'wordbook',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False, verbose_name='日時')),
                ('contents', models.TextField(verbose_name='会話内容')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.users', verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '会話',
                'verbose_name_plural': '会話',
                'db_table': 'chat',
                'ordering': ['-time'],
            },
        ),
    ]
